{{- if .Values.depot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depot-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app: depot-controller
    control-plane: controller
spec:
  replicas: {{ .Values.depot.replicaCount }}
  selector:
    matchLabels:
      app: depot-controller
      control-plane: controller
  template:
    metadata:
      labels:
        app: depot-controller
        control-plane: controller
    spec:
      serviceAccountName: depot-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
      - name: depot-controller
        image: "{{ .Values.depot.image.repository }}:{{ default (default .Chart.AppVersion .Values.global.image.tag) .Values.depot.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.rbac.scopeToNamespace }}
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.global.namespace }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          {{- toYaml .Values.depot.resources | nindent 10 }}
      {{- with .Values.depot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.depot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.depot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
