{{- if .Values.module.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app: module-controller
    control-plane: controller
spec:
  replicas: {{ .Values.module.replicaCount }}
  selector:
    matchLabels:
      app: module-controller
      control-plane: controller
  template:
    metadata:
      labels:
        app: module-controller
        control-plane: controller
    spec:
      serviceAccountName: module-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
      - name: deployment-controller
        image: "{{ .Values.module.image.repository }}:{{ default .Values.global.image.tag .Values.module.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.rbac.scopeToNamespace }}
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.global.namespace }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          {{- toYaml .Values.module.resources | nindent 10 }}
      {{- with .Values.module.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.module.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.module.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
