{{- if .Values.server.ingress.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opendepot-server
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
  {{- range .Values.server.ingress.istio.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ .Values.server.ingress.istio.gateway }}
  http:
  - name: opendepot-server
    route:
    - destination:
        host: server
        port:
          number: {{ .Values.server.service.port }}
{{- end }}