{{- if and .Values.server.enabled .Values.server.stats.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-stats
  namespace: {{ .Values.global.namespace }}
  labels:
    app: server
spec:
  accessModes:
    - {{ .Values.server.stats.persistence.accessMode }}
  {{- if .Values.server.stats.persistence.storageClassName }}
  storageClassName: {{ .Values.server.stats.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.stats.persistence.size }}
{{- end }}
