{{- if and .Values.storage.filesystem.enabled (not .Values.storage.filesystem.hostPath) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opendepot-modules
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: opendepot
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storage.filesystem.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.filesystem.size }}
{{- end }}
