apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: {{ .Values.global.namespace }}
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP
