{{- if .Values.valkey.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app: valkey
spec:
  accessModes:
    - {{ .Values.valkey.persistence.accessMode }}
  {{- if .Values.valkey.persistence.storageClassName }}
  storageClassName: {{ .Values.valkey.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.valkey.persistence.size }}
{{- end }}
