{{- if and .Values.depot.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.rbac.scopeToNamespace }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: depot-controller
  {{- if .Values.rbac.scopeToNamespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
rules:
- apiGroups:
  - kerrareg.io
  resources:
  - depots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kerrareg.io
  resources:
  - depots/finalizers
  verbs:
  - update
- apiGroups:
  - kerrareg.io
  resources:
  - depots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kerrareg.io
  resources:
  - modules
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.rbac.scopeToNamespace }}RoleBinding{{ else }}ClusterRoleBinding{{ end }}
metadata:
  name: depot-controller-role-binding
  {{- if .Values.rbac.scopeToNamespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.rbac.scopeToNamespace }}Role{{ else }}ClusterRole{{ end }}
  name: depot-controller
subjects:
- kind: ServiceAccount
  name: depot-controller
  namespace: {{ .Values.global.namespace }}
{{- end }}
