{{- if and .Values.version.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: version-controller-role
rules:
- apiGroups:
  - kerrareg.io
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kerrareg.io
  resources:
  - versions/finalizers
  verbs:
  - update
- apiGroups:
  - kerrareg.io
  resources:
  - versions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: version-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: version-controller-role
subjects:
- kind: ServiceAccount
  name: version-controller
  namespace: {{ .Values.global.namespace }}
{{- end }}
