apiVersion: v2
name: opendepot
description: A Helm chart for deploying OpenDepot, a cloud-native OpenTofu Registry
type: application
version: 0.2.3
appVersion: "0.2.3"
keywords:
  - terraform
  - opentofu
  - module-registry
  - provider-registry
  - kubernetes
maintainers:
  - name: Tony Owens
    email: tony.owens@defdev.io
