apiVersion: v2
name: opendepot
description: A Helm chart for deploying OpenDepot, a cloud-native OpenTofu Registry
type: application
version: 0.9.0
appVersion: "0.9.0"
keywords:
  - terraform
  - opentofu
  - module-registry
  - provider-registry
  - kubernetes
maintainers:
  - name: Tony Owens
    email: tony.owens@defdev.io
dependencies:
  - name: dex
    version: "0.24.*"
    repository: https://charts.dexidp.io
    condition: dex.enabled
  - name: valkey
    version: "0.9.*"
    repository: https://valkey-io.github.io/valkey-helm/
    condition: server.enabled
