// Code generated by "stringer -type=OpenDepotType"; DO NOT EDIT.

package v1alpha1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeModule-0]
	_ = x[TypeProvider-1]
}

const _OpenDepotType_name = "ModuleProvider"

var _OpenDepotType_index = [...]uint8{0, 6, 14}

func (i OpenDepotType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpenDepotType_index)-1 {
		return "OpenDepotType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpenDepotType_name[_OpenDepotType_index[idx]:_OpenDepotType_index[idx+1]]
}
