//go:build !ignore_autogenerated

/*
Copyright 2025 Anthony Owens.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMetadata) DeepCopyInto(out *AgentMetadata) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMetadata.
func (in *AgentMetadata) DeepCopy() *AgentMetadata {
	if in == nil {
		return nil
	}
	out := new(AgentMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSourceConfig) DeepCopyInto(out *AgentSourceConfig) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RepoUrl != nil {
		in, out := &in.RepoUrl, &out.RepoUrl
		*out = new(string)
		**out = **in
	}
	if in.TagPrefix != nil {
		in, out := &in.TagPrefix, &out.TagPrefix
		*out = new(string)
		**out = **in
	}
	if in.GithubClientConfig != nil {
		in, out := &in.GithubClientConfig, &out.GithubClientConfig
		*out = new(GithubClientConfig)
		**out = **in
	}
	if in.StorageConfig != nil {
		in, out := &in.StorageConfig, &out.StorageConfig
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Immutable != nil {
		in, out := &in.Immutable, &out.Immutable
		*out = new(bool)
		**out = **in
	}
	if in.VersionHistoryLimit != nil {
		in, out := &in.VersionHistoryLimit, &out.VersionHistoryLimit
		*out = new(int)
		**out = **in
	}
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(string)
		**out = **in
	}
	if in.JevSecretRef != nil {
		in, out := &in.JevSecretRef, &out.JevSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.JevPolicy != nil {
		in, out := &in.JevPolicy, &out.JevPolicy
		*out = new(JevPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSourceConfig.
func (in *AgentSourceConfig) DeepCopy() *AgentSourceConfig {
	if in == nil {
		return nil
	}
	out := new(AgentSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.AgentSourceConfig.DeepCopyInto(&out.AgentSourceConfig)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]AgentVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.VersionRefs != nil {
		in, out := &in.VersionRefs, &out.VersionRefs
		*out = make(map[string]*AgentVersion, len(*in))
		for key, val := range *in {
			var outVal *AgentVersion
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(AgentVersion)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentVersion) DeepCopyInto(out *AgentVersion) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentVersion.
func (in *AgentVersion) DeepCopy() *AgentVersion {
	if in == nil {
		return nil
	}
	out := new(AgentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmazonS3Config) DeepCopyInto(out *AmazonS3Config) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmazonS3Config.
func (in *AmazonS3Config) DeepCopy() *AmazonS3Config {
	if in == nil {
		return nil
	}
	out := new(AmazonS3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureStorageConfig) DeepCopyInto(out *AzureStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureStorageConfig.
func (in *AzureStorageConfig) DeepCopy() *AzureStorageConfig {
	if in == nil {
		return nil
	}
	out := new(AzureStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryScan) DeepCopyInto(out *BinaryScan) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]SecurityFinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryScan.
func (in *BinaryScan) DeepCopy() *BinaryScan {
	if in == nil {
		return nil
	}
	out := new(BinaryScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractConfigMapRef) DeepCopyInto(out *ContractConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractConfigMapRef.
func (in *ContractConfigMapRef) DeepCopy() *ContractConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ContractConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Depot) DeepCopyInto(out *Depot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Depot.
func (in *Depot) DeepCopy() *Depot {
	if in == nil {
		return nil
	}
	out := new(Depot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Depot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepotList) DeepCopyInto(out *DepotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Depot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepotList.
func (in *DepotList) DeepCopy() *DepotList {
	if in == nil {
		return nil
	}
	out := new(DepotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DepotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepotSpec) DeepCopyInto(out *DepotSpec) {
	*out = *in
	if in.GlobalConfig != nil {
		in, out := &in.GlobalConfig, &out.GlobalConfig
		*out = new(GlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ModuleConfigs != nil {
		in, out := &in.ModuleConfigs, &out.ModuleConfigs
		*out = make([]ModuleConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProviderConfigs != nil {
		in, out := &in.ProviderConfigs, &out.ProviderConfigs
		*out = make([]ProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SkillConfigs != nil {
		in, out := &in.SkillConfigs, &out.SkillConfigs
		*out = make([]AgentSourceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentConfigs != nil {
		in, out := &in.AgentConfigs, &out.AgentConfigs
		*out = make([]AgentSourceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PollingIntervalMinutes != nil {
		in, out := &in.PollingIntervalMinutes, &out.PollingIntervalMinutes
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepotSpec.
func (in *DepotSpec) DeepCopy() *DepotSpec {
	if in == nil {
		return nil
	}
	out := new(DepotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepotStatus) DeepCopyInto(out *DepotStatus) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepotStatus.
func (in *DepotStatus) DeepCopy() *DepotStatus {
	if in == nil {
		return nil
	}
	out := new(DepotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemConfig) DeepCopyInto(out *FileSystemConfig) {
	*out = *in
	if in.DirectoryPath != nil {
		in, out := &in.DirectoryPath, &out.DirectoryPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemConfig.
func (in *FileSystemConfig) DeepCopy() *FileSystemConfig {
	if in == nil {
		return nil
	}
	out := new(FileSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubClientConfig) DeepCopyInto(out *GithubClientConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubClientConfig.
func (in *GithubClientConfig) DeepCopy() *GithubClientConfig {
	if in == nil {
		return nil
	}
	out := new(GithubClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.GithubClientConfig != nil {
		in, out := &in.GithubClientConfig, &out.GithubClientConfig
		*out = new(GithubClientConfig)
		**out = **in
	}
	if in.ModuleConfig != nil {
		in, out := &in.ModuleConfig, &out.ModuleConfig
		*out = new(ModuleConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageConfig != nil {
		in, out := &in.StorageConfig, &out.StorageConfig
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudStorageConfig) DeepCopyInto(out *GoogleCloudStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudStorageConfig.
func (in *GoogleCloudStorageConfig) DeepCopy() *GoogleCloudStorageConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBinding) DeepCopyInto(out *GroupBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBinding.
func (in *GroupBinding) DeepCopy() *GroupBinding {
	if in == nil {
		return nil
	}
	out := new(GroupBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBindingExprEnv) DeepCopyInto(out *GroupBindingExprEnv) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBindingExprEnv.
func (in *GroupBindingExprEnv) DeepCopy() *GroupBindingExprEnv {
	if in == nil {
		return nil
	}
	out := new(GroupBindingExprEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBindingList) DeepCopyInto(out *GroupBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GroupBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBindingList.
func (in *GroupBindingList) DeepCopy() *GroupBindingList {
	if in == nil {
		return nil
	}
	out := new(GroupBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBindingSpec) DeepCopyInto(out *GroupBindingSpec) {
	*out = *in
	if in.ModuleResources != nil {
		in, out := &in.ModuleResources, &out.ModuleResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProviderResources != nil {
		in, out := &in.ProviderResources, &out.ProviderResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SkillResources != nil {
		in, out := &in.SkillResources, &out.SkillResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentResources != nil {
		in, out := &in.AgentResources, &out.AgentResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScanPolicyNamespaces != nil {
		in, out := &in.ScanPolicyNamespaces, &out.ScanPolicyNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBindingSpec.
func (in *GroupBindingSpec) DeepCopy() *GroupBindingSpec {
	if in == nil {
		return nil
	}
	out := new(GroupBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupBindingStatus) DeepCopyInto(out *GroupBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupBindingStatus.
func (in *GroupBindingStatus) DeepCopy() *GroupBindingStatus {
	if in == nil {
		return nil
	}
	out := new(GroupBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JevAssessment) DeepCopyInto(out *JevAssessment) {
	*out = *in
	if in.SafeProbability != nil {
		in, out := &in.SafeProbability, &out.SafeProbability
		*out = new(float64)
		**out = **in
	}
	if in.InjectionProbability != nil {
		in, out := &in.InjectionProbability, &out.InjectionProbability
		*out = new(float64)
		**out = **in
	}
	if in.ExfiltrationProbability != nil {
		in, out := &in.ExfiltrationProbability, &out.ExfiltrationProbability
		*out = new(float64)
		**out = **in
	}
	if in.DestructiveProbability != nil {
		in, out := &in.DestructiveProbability, &out.DestructiveProbability
		*out = new(float64)
		**out = **in
	}
	if in.HiddenInstructionsProbability != nil {
		in, out := &in.HiddenInstructionsProbability, &out.HiddenInstructionsProbability
		*out = new(float64)
		**out = **in
	}
	if in.ScopeMismatchProbability != nil {
		in, out := &in.ScopeMismatchProbability, &out.ScopeMismatchProbability
		*out = new(float64)
		**out = **in
	}
	if in.RemoteExecutionProbability != nil {
		in, out := &in.RemoteExecutionProbability, &out.RemoteExecutionProbability
		*out = new(float64)
		**out = **in
	}
	if in.RiskScore != nil {
		in, out := &in.RiskScore, &out.RiskScore
		*out = new(float64)
		**out = **in
	}
	if in.RiskConfidence != nil {
		in, out := &in.RiskConfidence, &out.RiskConfidence
		*out = new(float64)
		**out = **in
	}
	if in.BlockReasons != nil {
		in, out := &in.BlockReasons, &out.BlockReasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JevAssessment.
func (in *JevAssessment) DeepCopy() *JevAssessment {
	if in == nil {
		return nil
	}
	out := new(JevAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JevPolicy) DeepCopyInto(out *JevPolicy) {
	*out = *in
	if in.MinSafeProbability != nil {
		in, out := &in.MinSafeProbability, &out.MinSafeProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxInjectionProbability != nil {
		in, out := &in.MaxInjectionProbability, &out.MaxInjectionProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxExfiltrationProbability != nil {
		in, out := &in.MaxExfiltrationProbability, &out.MaxExfiltrationProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxDestructiveProbability != nil {
		in, out := &in.MaxDestructiveProbability, &out.MaxDestructiveProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxHiddenInstructionsProbability != nil {
		in, out := &in.MaxHiddenInstructionsProbability, &out.MaxHiddenInstructionsProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxScopeMismatchProbability != nil {
		in, out := &in.MaxScopeMismatchProbability, &out.MaxScopeMismatchProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxRemoteExecutionProbability != nil {
		in, out := &in.MaxRemoteExecutionProbability, &out.MaxRemoteExecutionProbability
		*out = new(float64)
		**out = **in
	}
	if in.MaxRiskScore != nil {
		in, out := &in.MaxRiskScore, &out.MaxRiskScore
		*out = new(float64)
		**out = **in
	}
	if in.MinConfidence != nil {
		in, out := &in.MinConfidence, &out.MinConfidence
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JevPolicy.
func (in *JevPolicy) DeepCopy() *JevPolicy {
	if in == nil {
		return nil
	}
	out := new(JevPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Module) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfig) DeepCopyInto(out *ModuleConfig) {
	*out = *in
	if in.FileFormat != nil {
		in, out := &in.FileFormat, &out.FileFormat
		*out = new(string)
		**out = **in
	}
	if in.GithubClientConfig != nil {
		in, out := &in.GithubClientConfig, &out.GithubClientConfig
		*out = new(GithubClientConfig)
		**out = **in
	}
	if in.Immutable != nil {
		in, out := &in.Immutable, &out.Immutable
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RepoUrl != nil {
		in, out := &in.RepoUrl, &out.RepoUrl
		*out = new(string)
		**out = **in
	}
	if in.StorageConfig != nil {
		in, out := &in.StorageConfig, &out.StorageConfig
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VersionHistoryLimit != nil {
		in, out := &in.VersionHistoryLimit, &out.VersionHistoryLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfig.
func (in *ModuleConfig) DeepCopy() *ModuleConfig {
	if in == nil {
		return nil
	}
	out := new(ModuleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleList) DeepCopyInto(out *ModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleList.
func (in *ModuleList) DeepCopy() *ModuleList {
	if in == nil {
		return nil
	}
	out := new(ModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpec) DeepCopyInto(out *ModuleSpec) {
	*out = *in
	in.ModuleConfig.DeepCopyInto(&out.ModuleConfig)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ModuleVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpec.
func (in *ModuleSpec) DeepCopy() *ModuleSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.ModuleVersionRefs != nil {
		in, out := &in.ModuleVersionRefs, &out.ModuleVersionRefs
		*out = make(map[string]*ModuleVersion, len(*in))
		for key, val := range *in {
			var outVal *ModuleVersion
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ModuleVersion)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleVersion) DeepCopyInto(out *ModuleVersion) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleVersion.
func (in *ModuleVersion) DeepCopy() *ModuleVersion {
	if in == nil {
		return nil
	}
	out := new(ModuleVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresignConfig) DeepCopyInto(out *PresignConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FallbackToProxy != nil {
		in, out := &in.FallbackToProxy, &out.FallbackToProxy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresignConfig.
func (in *PresignConfig) DeepCopy() *PresignConfig {
	if in == nil {
		return nil
	}
	out := new(PresignConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistry != nil {
		in, out := &in.UpstreamRegistry, &out.UpstreamRegistry
		*out = new(string)
		**out = **in
	}
	if in.OperatingSystems != nil {
		in, out := &in.OperatingSystems, &out.OperatingSystems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GithubClientConfig != nil {
		in, out := &in.GithubClientConfig, &out.GithubClientConfig
		*out = new(GithubClientConfig)
		**out = **in
	}
	if in.SourceRepository != nil {
		in, out := &in.SourceRepository, &out.SourceRepository
		*out = new(string)
		**out = **in
	}
	if in.StorageConfig != nil {
		in, out := &in.StorageConfig, &out.StorageConfig
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VersionHistoryLimit != nil {
		in, out := &in.VersionHistoryLimit, &out.VersionHistoryLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfig.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSchemaRef) DeepCopyInto(out *ProviderSchemaRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSchemaRef.
func (in *ProviderSchemaRef) DeepCopy() *ProviderSchemaRef {
	if in == nil {
		return nil
	}
	out := new(ProviderSchemaRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSchemaStatus) DeepCopyInto(out *ProviderSchemaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSchemaStatus.
func (in *ProviderSchemaStatus) DeepCopy() *ProviderSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.ProviderConfig.DeepCopyInto(&out.ProviderConfig)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ProviderVersion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.ProviderVersionRefs != nil {
		in, out := &in.ProviderVersionRefs, &out.ProviderVersionRefs
		*out = make(map[string]*ProviderVersion, len(*in))
		for key, val := range *in {
			var outVal *ProviderVersion
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ProviderVersion)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderVersion) DeepCopyInto(out *ProviderVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderVersion.
func (in *ProviderVersion) DeepCopy() *ProviderVersion {
	if in == nil {
		return nil
	}
	out := new(ProviderVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadmeConfigMapRef) DeepCopyInto(out *ReadmeConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadmeConfigMapRef.
func (in *ReadmeConfigMapRef) DeepCopy() *ReadmeConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ReadmeConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanExemption) DeepCopyInto(out *ScanExemption) {
	*out = *in
	if in.VulnerabilityIDs != nil {
		in, out := &in.VulnerabilityIDs, &out.VulnerabilityIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PkgNames != nil {
		in, out := &in.PkgNames, &out.PkgNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScanTypes != nil {
		in, out := &in.ScanTypes, &out.ScanTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanExemption.
func (in *ScanExemption) DeepCopy() *ScanExemption {
	if in == nil {
		return nil
	}
	out := new(ScanExemption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicy) DeepCopyInto(out *ScanPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicy.
func (in *ScanPolicy) DeepCopy() *ScanPolicy {
	if in == nil {
		return nil
	}
	out := new(ScanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicyList) DeepCopyInto(out *ScanPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScanPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicyList.
func (in *ScanPolicyList) DeepCopy() *ScanPolicyList {
	if in == nil {
		return nil
	}
	out := new(ScanPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicySpec) DeepCopyInto(out *ScanPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]ScanPolicyTargetRef, len(*in))
		copy(*out, *in)
	}
	if in.Exemptions != nil {
		in, out := &in.Exemptions, &out.Exemptions
		*out = make([]ScanExemption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicySpec.
func (in *ScanPolicySpec) DeepCopy() *ScanPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScanPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicyStatus) DeepCopyInto(out *ScanPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicyStatus.
func (in *ScanPolicyStatus) DeepCopy() *ScanPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ScanPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanPolicyTargetRef) DeepCopyInto(out *ScanPolicyTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanPolicyTargetRef.
func (in *ScanPolicyTargetRef) DeepCopy() *ScanPolicyTargetRef {
	if in == nil {
		return nil
	}
	out := new(ScanPolicyTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityFinding) DeepCopyInto(out *SecurityFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityFinding.
func (in *SecurityFinding) DeepCopy() *SecurityFinding {
	if in == nil {
		return nil
	}
	out := new(SecurityFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupBinding) DeepCopyInto(out *SecurityGroupBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupBinding.
func (in *SecurityGroupBinding) DeepCopy() *SecurityGroupBinding {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupBindingList) DeepCopyInto(out *SecurityGroupBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityGroupBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupBindingList.
func (in *SecurityGroupBindingList) DeepCopy() *SecurityGroupBindingList {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupBindingSpec) DeepCopyInto(out *SecurityGroupBindingSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ModuleResources != nil {
		in, out := &in.ModuleResources, &out.ModuleResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProviderResources != nil {
		in, out := &in.ProviderResources, &out.ProviderResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SkillResources != nil {
		in, out := &in.SkillResources, &out.SkillResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentResources != nil {
		in, out := &in.AgentResources, &out.AgentResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupBindingSpec.
func (in *SecurityGroupBindingSpec) DeepCopy() *SecurityGroupBindingSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupBindingStatus) DeepCopyInto(out *SecurityGroupBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupBindingStatus.
func (in *SecurityGroupBindingStatus) DeepCopy() *SecurityGroupBindingStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skill) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillList) DeepCopyInto(out *SkillList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillList.
func (in *SkillList) DeepCopy() *SkillList {
	if in == nil {
		return nil
	}
	out := new(SkillList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSpec) DeepCopyInto(out *SkillSpec) {
	*out = *in
	in.AgentSourceConfig.DeepCopyInto(&out.AgentSourceConfig)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]SkillVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSpec.
func (in *SkillSpec) DeepCopy() *SkillSpec {
	if in == nil {
		return nil
	}
	out := new(SkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillStatus) DeepCopyInto(out *SkillStatus) {
	*out = *in
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.VersionRefs != nil {
		in, out := &in.VersionRefs, &out.VersionRefs
		*out = make(map[string]*SkillVersion, len(*in))
		for key, val := range *in {
			var outVal *SkillVersion
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(SkillVersion)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillStatus.
func (in *SkillStatus) DeepCopy() *SkillStatus {
	if in == nil {
		return nil
	}
	out := new(SkillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillVersion) DeepCopyInto(out *SkillVersion) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillVersion.
func (in *SkillVersion) DeepCopy() *SkillVersion {
	if in == nil {
		return nil
	}
	out := new(SkillVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceScan) DeepCopyInto(out *SourceScan) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]SecurityFinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceScan.
func (in *SourceScan) DeepCopy() *SourceScan {
	if in == nil {
		return nil
	}
	out := new(SourceScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.AzureStorage != nil {
		in, out := &in.AzureStorage, &out.AzureStorage
		*out = new(AzureStorageConfig)
		**out = **in
	}
	if in.FileSystem != nil {
		in, out := &in.FileSystem, &out.FileSystem
		*out = new(FileSystemConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(AmazonS3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GoogleCloudStorageConfig)
		**out = **in
	}
	if in.Presign != nil {
		in, out := &in.Presign, &out.Presign
		*out = new(PresignConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Version.
func (in *Version) DeepCopy() *Version {
	if in == nil {
		return nil
	}
	out := new(Version)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Version) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionList) DeepCopyInto(out *VersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Version, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionList.
func (in *VersionList) DeepCopy() *VersionList {
	if in == nil {
		return nil
	}
	out := new(VersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionSpec) DeepCopyInto(out *VersionSpec) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.AgentSourceRef != nil {
		in, out := &in.AgentSourceRef, &out.AgentSourceRef
		*out = new(AgentSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ModuleConfigRef != nil {
		in, out := &in.ModuleConfigRef, &out.ModuleConfigRef
		*out = new(ModuleConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(ProviderConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionSpec.
func (in *VersionSpec) DeepCopy() *VersionSpec {
	if in == nil {
		return nil
	}
	out := new(VersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionStatus) DeepCopyInto(out *VersionStatus) {
	*out = *in
	if in.Checksum != nil {
		in, out := &in.Checksum, &out.Checksum
		*out = new(string)
		**out = **in
	}
	if in.ArchiveSizeBytes != nil {
		in, out := &in.ArchiveSizeBytes, &out.ArchiveSizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.BinaryScan != nil {
		in, out := &in.BinaryScan, &out.BinaryScan
		*out = new(BinaryScan)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceScan != nil {
		in, out := &in.SourceScan, &out.SourceScan
		*out = new(SourceScan)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadmeConfigMapRef != nil {
		in, out := &in.ReadmeConfigMapRef, &out.ReadmeConfigMapRef
		*out = new(ReadmeConfigMapRef)
		**out = **in
	}
	if in.ContractConfigMapRef != nil {
		in, out := &in.ContractConfigMapRef, &out.ContractConfigMapRef
		*out = new(ContractConfigMapRef)
		**out = **in
	}
	if in.ProviderSchemaRef != nil {
		in, out := &in.ProviderSchemaRef, &out.ProviderSchemaRef
		*out = new(ProviderSchemaRef)
		**out = **in
	}
	if in.ProviderSchemaStatus != nil {
		in, out := &in.ProviderSchemaStatus, &out.ProviderSchemaStatus
		*out = new(ProviderSchemaStatus)
		**out = **in
	}
	if in.AgentMetadata != nil {
		in, out := &in.AgentMetadata, &out.AgentMetadata
		*out = new(AgentMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.JevAssessment != nil {
		in, out := &in.JevAssessment, &out.JevAssessment
		*out = new(JevAssessment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionStatus.
func (in *VersionStatus) DeepCopy() *VersionStatus {
	if in == nil {
		return nil
	}
	out := new(VersionStatus)
	in.DeepCopyInto(out)
	return out
}
