apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendepot-portal
  namespace: opendepot-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendepot-portal
  template:
    metadata:
      labels:
        app: opendepot-portal
    spec:
      serviceAccountName: opendepot-portal
      containers:
        - name: portal
          image: ghcr.io/tonedefdev/opendepot/portal:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENDEPOT_NAMESPACE
              value: opendepot-system
            - name: OPENDEPOT_K8S_AUTH_MODE
              value: incluster
            - name: PORT
              value: "8081"
          ports:
            - containerPort: 8081
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: opendepot-portal
  namespace: opendepot-system
spec:
  selector:
    app: opendepot-portal
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
