apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendepot-portal
  namespace: opendepot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opendepot-portal-readonly
  namespace: opendepot-system
rules:
  - apiGroups: ["opendepot.defdev.io"]
    resources: ["depots", "modules", "versions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opendepot-portal-readonly
  namespace: opendepot-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opendepot-portal-readonly
subjects:
  - kind: ServiceAccount
    name: opendepot-portal
    namespace: opendepot-system
