apiVersion: opendepot.defdev.io/v1alpha1
kind: Depot
metadata:
  name: ui-demo-depot
  namespace: opendepot-system
spec:
  global:
    moduleConfig:
      fileFormat: zip
      immutable: true
    storageConfig:
      fileSystem:
        directoryPath: /data/modules
  moduleConfigs:
    - name: terraform-aws-acm
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-acm
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-api-gateway
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-api-gateway
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-cloudfront
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-cloudfront
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-ecr
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-ecr
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-iam
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-iam
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-lambda
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-lambda
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-s3
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-s3
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-secrets-manager
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-secrets-manager
      versionConstraints: ">= 0.0.0"
    - name: terraform-aws-ses
      provider: aws
      repoOwner: defdevio
      repoUrl: https://github.com/defdevio/terraform-aws-ses
      versionConstraints: ">= 0.0.0"
  pollingIntervalMinutes: 60
  providerConfigs:
    - name: aws
      architectures:
        - arm64
      operatingSystems:
        - darwin
        - linux
      versionConstraints: "~> 6.60.0"
---
apiVersion: opendepot.defdev.io/v1alpha1
kind: GroupBinding
metadata:
  name: quickstart-public-access
  namespace: opendepot-system
spec:
  expression: "true"
  moduleResources:
    - "*"
  providerResources:
    - "*"
