name: Docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - CONTRIBUTING.md
      - chart/opendepot/README.md

jobs:
  deploy:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install system dependencies for social cards
        run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev

      - name: Install MkDocs dependencies
        run: pip install -r requirements.txt

      - name: Prepare docs
        run: |
          cp CONTRIBUTING.md docs/contributing.md
          cp chart/opendepot/README.md docs/helm-chart.md

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
